name: Notify Local Webhook For different machines

on:
  push:
    branches:
      - main
      - merge_with_me
      - use_me_to_merge

jobs:
  notify-local:
    runs-on: ubuntu-latest
    steps:
      - name: Set webhook URL based on branch
        id: set-url
        run: |
          echo "GITHUB_REF=${GITHUB_REF}"
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "url=http://20.187.146.225/webhook" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "merge_with_me" ]]; then
            echo "url=http://174.176.208.144/webhook" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "use_me_to_merge" ]]; then
            echo "url=http://10.0.0.3/webhook" >> $GITHUB_OUTPUT
          else
            echo "url=http://default-host/webhook" >> $GITHUB_OUTPUT
          fi

      - name: Send POST to Local Machine Webhook
        run: |
          curl -X POST ${{ steps.set-url.outputs.url }} \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: push" \
            -d '{}'
