name: Merge changedetection.io and push to my-node-app

on:
  workflow_dispatch:

jobs:
  merge-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout temporary working branch
        uses: actions/checkout@v4
        with:
          ref: blogs-daily
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add changedetection.io as remote and fetch
        run: |
          git remote add changedetection https://github.com/dgtlmoon/changedetection.io.git
          git fetch changedetection master --depth=1
          echo "Fetched changedetection/master"

      - name: Merge changedetection/master into blogs-daily branch (auto-resolve conflicts)
        run: |
          git merge -X theirs changedetection/master --allow-unrelated-histories -m "Daily merge from changedetection.io" || \
          (echo "Merge failed, resolving all conflicts with 'theirs' strategy" && \
           git checkout --theirs . && \
           git add . && \
           git commit -m "Conflict resolved using theirs strategy")
          git push origin blogs-daily

      - name: Push merged blogs-daily branch to my-node-app repo
        env:
          TARGET_REPO_URL: https://Abinavharsha:${{ secrets.MY_NODE_APP_PAT }}@github.com/Abinavharsha/my-node-app.git
        run: |
          git remote add deploy "$TARGET_REPO_URL"
          git push deploy blogs-daily:main --force

