name: Auto Merge

on:
  pull_request:
    types: [closed]

jobs:
  merge_check:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm test
      - name: Build Project
        run: npm run build
      - name:  Merge Confirmation
        run: echo "Pull request merged successfully!"
