name: Merge changedetection.io into blogs-daily branch

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  merge-headlines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout blogs-daily branch
        uses: actions/checkout@v4
        with:
          ref: blogs-daily
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add changedetection.io as remote and fetch
        run: |
          git remote add changedetection https://github.com/dgtlmoon/changedetection.io.git
          git fetch changedetection master --depth=1
          echo "Remote branches:"
          git branch -r

      - name: Merge changedetection/master into blogs-daily
        run: |
          git merge changedetection/master --allow-unrelated-histories -m "Daily merge from changedetection.io"
          git push origin blogs-daily
