name: SSH Git Pull Per Branch

on:
  push:
    branches:
      - main
      - dev
      - qa

jobs:
  ssh-pull:
    runs-on: ubuntu-latest

    steps:
      - name: Set Host, Branch, Username
        id: set-vars
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "Branch: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "host=20.187.146.225" >> $GITHUB_OUTPUT
            echo "user=batman" >> $GITHUB_OUTPUT
            echo "branch=main" >> $GITHUB_OUTPUT
            echo "key_secret=SSH1_PRIVATE_KEY" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH_NAME" == "dev" ]]; then
            echo "host=135.116.64.27" >> $GITHUB_OUTPUT
            echo "user=githubtester" >> $GITHUB_OUTPUT
            echo "branch=dev" >> $GITHUB_OUTPUT
            echo "key_secret=SSH2_PRIVATE_KEY" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH_NAME" == "qa" ]]; then
            echo "host=72.146.152.65" >> $GITHUB_OUTPUT
            echo "user=githutester2" >> $GITHUB_OUTPUT
            echo "branch=qa" >> $GITHUB_OUTPUT
            echo "key_secret=SSH3_PRIVATE_KEY" >> $GITHUB_OUTPUT
          else
            echo "Unsupported branch: $BRANCH_NAME"
            exit 1
          fi

      - name: Set up SSH
        env:
          SSH_KEY: ${{ secrets[steps.set-vars.outputs.key_secret] }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ steps.set-vars.outputs.host }} >> ~/.ssh/known_hosts

      - name: SSH and Git Pull
        env:
          HOST: ${{ steps.set-vars.outputs.host }}
          USER: ${{ steps.set-vars.outputs.user }}
          BRANCH: ${{ steps.set-vars.outputs.branch }}
        run: |
          ssh $USER@$HOST <<EOF
            cd /home/$USER/my-node-app
            git checkout $BRANCH
            git pull origin $BRANCH
          EOF
